spring.application.name=reports_registration
server.port=${SERVER_PORT:8082}
books.service.url=${BOOKS_SERVICE_URL:http://localhost:8081}
genres.service.url=${GENRES_SERVICE_URL:http://localhost:8080}
